### PR TITLE
fixes: #76bug add validation for all input field's

### LINKED ISSUE #76: BUG:  No proper validation for adding youtube channel
steps to reproduce bug :
1. Go to add youtubers page
2. type random catagory name birthday and in all input fields.

youtube
youtube22

how to fix you have to add a proper validation in all field's

### PR DESCRIPTION
**Pull request by love-sonkar**
fixes #76 added validation in all input field's and for the category i use a dropdown selection for better user experiance and for validation.
you

### CODE REVIEW

File: public/validation.js [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+  "Gaming",
+  "People and Blogs",
+  "Comedy",
+  "Entertainment",
+  "News and Politics",
+  "Education",
+  "Science and Technology",
+  "How-to and Style",
+  "Nonprofits and Activism",
+];
```
Comment (MayankBansal12) [inline public/validation.js:20]: You can add one more category "Others" and in the music category remove that extra space.

File: public/validation.js [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+          totalViewserror.innerText = "Not have Enough subscriber";
+        } else {
+          totalViewserror.innerText = "";
+        }
+      }
+    }
+  }
+
+  //validation code for youtublink
+  const urlregex = /^https:\/\/www\.youtube\.com\/watch$/i;
```
Comment (MayankBansal12) [inline public/validation.js:118]: The URL for a channel can either be https://www.youtube.com/c/Name or https://www.youtube.com/@Name.
Adding /watch may not approve these, so take care of this.

Comment (love-sonkar) [reply public/validation.js:118]: okay, im going to do some changes in url the link can be a channel link or it can be any video link

File: public/validation.js [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+
+  youtublink.trim();
+  if (youtublink.length < 1) {
+    youtublinkerror.innerText = "Link Can't be empty";
+  } else {
+    const inputlinkslice = youtublink.slice(0, 29);
+    const validateLink = urlregex.test(inputlinkslice);
+    if (validateLink) {
+      // second check for link
+      const accepted = inputlinkslice === "https://www.youtube.com/watch";
```
Comment (MayankBansal12) [inline public/validation.js:128]: /watch is used for videos. For channels, endpoint is different.

**Review by MayankBansal12 — CHANGES_REQUESTED** [review]
- Make sure all the functions are working properly. 
- After making the changes, make sure the code is not broken or getting affected due to changes. - Also, try to check everything is working by adding a few entries from your end.

File: public/validation.js [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+  if (birthday.length < 1) {
+    birthdayerror.innerText = "Birthday Can't be empty";
+  } else {
+    if (GetAge() < 5) {
+      birthdayerror.innerText = "Age can't be Less then 5 ";
+    } else {
+      birthdayerror.innerText = "";
+    }
+  }
+
```
[the remark this answers is not in the document]
Comment (love-sonkar) [reply public/validation.js:82]: i know but for desplaying some error msg, i have to check one property so i removed the age calculation and just checking if birthday is null or not 
bb

**Comment by KendallDoesCoding** [comment]
@MayankBansal12 are we good to merge?

File: public/validation.js [hunk 5]
```diff
@@ -0,0 +1,139 @@
+/// add validataion when user enter any youtuber's birthday
+
+// category list of all youtube category
+const categoryList = [
```
Comment (MayankBansal12) [inline public/validation.js:4]: In the Category List, can you add previous categories that have been used before like Finance, Tech, Kids etc.?
Along with the new categories you have added, we should keep the previous categories too.

**Review by MayankBansal12 — CHANGES_REQUESTED** [review]
You only need to modify the add categories. Other than that, everything else looks good.

File: public/validation.js (hunk 5 above)
Comment (love-sonkar) [reply public/validation.js:4]: okey can you send me the previous categories list then i will add all the list in the categories

Comment (MayankBansal12) [reply public/validation.js:4]: We haven't made any category list before, but you can check the site for the previous entries and see the categories there.

Comment (love-sonkar) [reply public/validation.js:4]: Ok, I will look at the website and add as many categories as there are.

**Review by MayankBansal12 — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@love-sonkar - thanks for your contribution!
